[package]
name = "svix-bridge-plugin-queue"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures-lite = "1.12.0"
omniqueue = { git = "https://github.com/svix/omniqueue-rs", rev = "247904053bcf90cf693df4429092923bf97770eb" }
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
svix-bridge-types = { path = "../svix-bridge-types" }
tokio = { version = "1", features = ["full"] }
tokio-executor-trait = "2.1"
tokio-reactor-trait = "1.1"
tracing = "0.1"

[dev-dependencies]
aws-config = "0.55"
aws-sdk-sqs = "0.25"
fastrand = "1.9"
google-cloud-googleapis = "0.10.0"
google-cloud-pubsub = "0.18.0"
lapin = "2"
redis = { version = "0.21", features = ["tokio-comp", "streams"] }
tracing-subscriber = "0.3"
wiremock = "0.5.18"